### Login
POST {{BASE_URL}}/jwt-auth/v1/token
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "Yao123"
}

### Profile
POST {{BASE_URL}}/wp/v2/users/me
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


### get home icon menus
GET {{BASE_URL}}/oms/v1/menus
Accept: application/json
Content-Type: application/json

### get orders
GET {{BASE_URL}}/oms/v1/orders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "status": "processing",
  "keyword": "",
  "per_page": 2
}

### update order
PUT {{BASE_URL}}/oms/v1/orders/22
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "status": "pendding"
}

### get order item
GET {{BASE_URL}}/oms/v1/orders/1/items/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "status": "pendding"
}

### Delete order item featured image
DELETE {{BASE_URL}}/oms/v1/order-items/4/image
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### PrintOrder
GET {{BASE_URL}}/oms/v1/print/orders/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{TOKEN}}